/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uzduociu_sarasas;

import com.sun.org.apache.xml.internal.utils.StringComparable;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import org.apache.derby.iapi.sql.compile.CompilerContext;

/**
 *
 * @author Paulius
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    Connection prisijungimas=null;
ResultSet rezultatas=null;
PreparedStatement pstmnt=null;
    public GUI() {
        initComponents();
        prisijungimas = Uzduociu_sarasas.Prisijungti();
        rodymas();
        combo();
        
    }
public void rodymas()
{
    try{
    String sql="select * from UZDUOCIUDB";
pstmnt=prisijungimas.prepareStatement(sql);
rezultatas=pstmnt.executeQuery();
jTable1.setModel(DbUtils.resultSetToTableModel(rezultatas));
}
catch(Exception e){
//JOptionPane.showMessageDialog(null, e.getMessage());
}
finally{
    try{
        rezultatas.close();
        pstmnt.close();         
    }
    catch(Exception e){}}
}
public void vardas(String sk)
{ String naujas=null;
    naujas=sk;
   // System.out.println(naujas);
//useris.setText(naujas);
String k=null;
k = naujas.toUpperCase().substring(0, (naujas.length()- (naujas.length()-1)) );
usertxt.setText(" Vartotojas : " + k+naujas.substring(1));
    }
private void combo()
{
    try{
        String sql="select * from vartotojaidb where vardas!= 'rimas' ";
        pstmnt=prisijungimas.prepareStatement(sql);
        rezultatas=pstmnt.executeQuery();
        while(rezultatas.next())
        {String veikejas = rezultatas.getString("vardas");
        priskirimascombo.addItem(veikejas);}
    }catch(Exception ex)
    {JOptionPane.showMessageDialog(null, ex);}
}
private void naujinimas()
    {
        String sql="select * from UZDUOCIUDB";
        try
        {
            pstmnt=prisijungimas.prepareStatement(sql);
            rezultatas =pstmnt.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rezultatas));
        }catch(Exception e)
        {JOptionPane.showMessageDialog(null,e);}finally{try{rezultatas.close();pstmnt.close();}catch(Exception e){}}
    }
  public void close()
    {
        WindowEvent uzdarymas = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(uzdarymas);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        uzduotistxt = new javax.swing.JTextField();
        priskirimascombo = new javax.swing.JComboBox<>();
        sukurtitxt = new javax.swing.JButton();
        priskirtimgt = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        istrintibtn = new javax.swing.JButton();
        usertxt = new javax.swing.JLabel();
        busenatxt = new javax.swing.JTextField();
        uzduotispriskirimastxt = new javax.swing.JTextField();
        busenaslider = new javax.swing.JSlider();
        pareiga = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Užduotis", "Užduoties priskirimas", "Vykdančiojo pareigos", "Busena"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("ID");

        jLabel2.setText("Užduotis");

        jLabel3.setText("Užduoties priskirimas");

        jLabel5.setText("Būsena");

        idtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtActionPerformed(evt);
            }
        });

        uzduotistxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uzduotistxtActionPerformed(evt);
            }
        });

        priskirimascombo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                priskirimascomboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        sukurtitxt.setText("Sukurti");
        sukurtitxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sukurtitxtActionPerformed(evt);
            }
        });

        priskirtimgt.setText("Priskirti");
        priskirtimgt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priskirtimgtActionPerformed(evt);
            }
        });

        jButton3.setText("Redaguoti");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        istrintibtn.setText("Ištrinti");
        istrintibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                istrintibtnActionPerformed(evt);
            }
        });

        usertxt.setBackground(new java.awt.Color(0, 0, 153));
        usertxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usertxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usertxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        uzduotispriskirimastxt.setForeground(new java.awt.Color(255, 255, 255));
        uzduotispriskirimastxt.setBorder(null);

        busenaslider.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        busenaslider.setMajorTickSpacing(100);
        busenaslider.setPaintLabels(true);
        busenaslider.setPaintTicks(true);

        pareiga.setForeground(new java.awt.Color(255, 255, 255));
        pareiga.setBorder(null);
        pareiga.setCaretColor(new java.awt.Color(255, 255, 255));

        jMenu1.setText("File");

        jMenuItem1.setText("Atsijungti");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pareiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(107, 107, 107)
                                .addComponent(busenaslider, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(priskirimascombo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(busenatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uzduotistxt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3)
                                    .addComponent(istrintibtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(priskirtimgt, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sukurtitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(uzduotispriskirimastxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uzduotispriskirimastxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(pareiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(usertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(8, 8, 8))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(uzduotistxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(priskirimascombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addComponent(busenaslider, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(busenatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sukurtitxt)
                            .addComponent(jButton3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priskirtimgt)
                            .addComponent(istrintibtn))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtxtActionPerformed

    private void uzduotistxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uzduotistxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uzduotistxtActionPerformed

    private void priskirimascomboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_priskirimascomboPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String tmp = (String)priskirimascombo.getSelectedItem();
         
           //String TableClick=(Projektulentelevadov.getModel().getValueAt(row,0).toString());
/**
       String sql="select * from VARTOTOJAIDB WHERE VARDAS=?";
        try
        {
            pstmnt=prisijungimas.prepareStatement(sql);
            pstmnt.setString(1,tmp);
            rezultatas=pstmnt.executeQuery();
            if(rezultatas.next())
            {String add1=rezultatas.getString("ID");
               txtID.setText(add1);
               String add2=rezultatas.getString("PROJEKTOPAVADINIMAS");
               txtName.setText(add2);
               String add3=rezultatas.getString("PROJEKTOAPRASAS");
               txtAbout.setText(add3);
               String add4=rezultatas.getString("PROJEKTOPRADZIA");
               txtStart.setText(add4);
               String add5=rezultatas.getString("PROJEKTOPABAIGA");
               txtEnd.setText(add5);
               String add6=rezultatas.getString("KLIENTAS");
               txtClient.setText(add6);}
        
         //  updateTable();
        }catch(Exception e)
        {JOptionPane.showMessageDialog(null, e);
                }finally
        {try{
        pstmnt.close(); rezultatas.close();
        }catch(Exception e){};
        } */
    }//GEN-LAST:event_priskirimascomboPopupMenuWillBecomeInvisible

    private void sukurtitxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sukurtitxtActionPerformed
        // TODO add your handling code here:
       try{
     int reiksme = busenaslider.getValue();
     if(reiksme!=100)
     {busenatxt.setText("false");}
     else busenatxt.setText("true");
    // int skaicius = priskirimascombo.getSelectedItem();
        String sql="insert into UZDUOCIUDB(ID,UZDUOTIS,UZDUOTIESPRISKIRIMAS,"
            + "VYKDANCIOJOPAREIGOS,BUSENA)values(?,?,?,?,?)";
    String skaicius = priskirimascombo.getSelectedItem().toString();
    uzduotispriskirimastxt.setText(skaicius);
   //String pareigosstr ="select * FROM VARTOTOJAIDB WHERE ID = '"+uzduotispriskirimastxt+"' ";
   String temp=null; 
   if("tomas".equals(skaicius))
    {temp="Programuotojas";}
        else if("simas".equals(skaicius)){
              temp="Front-end programuotojas";  
   }  else if("kristina".equals(skaicius)){
              temp="Back-end programuotojas";  
   }else if("ugne".equals(skaicius)){
              temp="Testuotoja";  
   }
    pareiga.setText(temp);
    pstmnt=prisijungimas.prepareStatement(sql);
    pstmnt.setString(1, idtxt.getText());
    pstmnt.setString(2, uzduotistxt.getText());
    pstmnt.setString(3,uzduotispriskirimastxt.getText());
    pstmnt.setString(4, pareiga.getText());
    pstmnt.setString(5,busenatxt.getText());
  //  pstmnt.setString(5, txtEnd.getText());
    pstmnt.execute();
    JOptionPane.showMessageDialog(null, "Issaugota");
    
}   
catch(Exception e){JOptionPane.showMessageDialog(null, e);
}
    }//GEN-LAST:event_sukurtitxtActionPerformed

    private void istrintibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_istrintibtnActionPerformed
        // TODO add your handling code here:
       int p = JOptionPane.showConfirmDialog(null,"Do you really want to delete?", "Delete", JOptionPane.YES_NO_OPTION); 
        if(p==0)
        {
                int row=jTable1.getSelectedRow();
        System.out.println(row);
        String cell = jTable1.getModel().getValueAt(row, 0).toString();
        String sql="DELETE FROM UZDUOCIUDB where ID="+ cell;
        try
        {
            pstmnt=prisijungimas.prepareStatement(sql);
            pstmnt.execute();
            JOptionPane.showMessageDialog(null,"Istrinta");
         naujinimas();
        
        }catch(Exception e)
        {JOptionPane.showMessageDialog(null, e);
                }finally
        {try{
        pstmnt.close(); rezultatas.close();
        }catch(Exception e){};
        }}
    }//GEN-LAST:event_istrintibtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        try
        {
            int row =jTable1.getSelectedRow();
          //  String TableClick=(jTable1.getModel().getValueAt(row,0).toString());
          //  String sql = "select * from UZDUOCIUDB where id='"+TableClick+"'";
        //    pstmnt=prisijungimas.prepareCall(sql);
        //    rezultatas=pstmnt.executeQuery();
        //    if(rezultatas.next())
         //   {String tekst1=rezultatas.getString("id");
       //      idtxt.setText(tekst1);
        //     String tekst2=rezultatas.getString("uzduotis");
             //uzduotistxt.setText(tekst2);
             //String tekst3=rezultatas.getString("uzduotiespriskirimas");
            // uzduotispriskirimastxt.setText(tekst3);
           //  String tekst4=rezultatas.getString("vykdanciojopareigos");
            // pareiga.setText(tekst4);
            // String tekst5=rezultatas.getString("busena");
            // busenatxt.setText(tekst5);
                    
            idtxt.setText(jTable1.getModel().getValueAt(row,0).toString());
            uzduotistxt.setText(jTable1.getModel().getValueAt(row,1).toString());
            uzduotispriskirimastxt.setText(jTable1.getModel().getValueAt(row,2).toString());
           // pareiga.setText(jTable1.getModel().getValueAt(row,3).toString());
            busenatxt.setText(jTable1.getModel().getValueAt(row,4).toString());
            
        }catch(Exception ex)
        {JOptionPane.showMessageDialog(null,ex);}
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void priskirtimgtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priskirtimgtActionPerformed
        // TODO add your handling code here:
        try{
        //String sql="insert into UZDUOCIUDB(ID,UZDUOTIESPRISKIRIMAS,"
          //  + "VYKDANCIOJOPAREIGOS)values(?,?,?)";
    String skaicius = priskirimascombo.getSelectedItem().toString();
    uzduotispriskirimastxt.setText(skaicius);
   //String pareigosstr ="select * FROM VARTOTOJAIDB WHERE ID = '"+uzduotispriskirimastxt+"' ";
   String temp=null; 
   if("tomas".equals(skaicius))
    {temp="Programuotojas";}
        else if("simas".equals(skaicius)){
              temp="Front-end programuotojas";  
   }  else if("kristina".equals(skaicius)){
              temp="Back-end programuotojas";  
   }else if("ugne".equals(skaicius)){
              temp="Testuotoja";  
   }
    pareiga.setText(temp);
    //pstmnt=prisijungimas.prepareStatement(sql);
           String value1= idtxt.getText();
      //     int val1=Integer.parseInt(value1);
           String value3=uzduotispriskirimastxt.getText();
           String value4=pareiga.getText();
           String value5="false";
           String sql="UPDATE UZDUOCIUDB set ID="+ value1+",UZDUOTIESPRISKIRIMAS='"+value3+"',VYKDANCIOJOPAREIGOS='"+value4+"',BUSENA='"+value5+"' WHERE ID="+value1+""; 
           pstmnt=prisijungimas.prepareStatement(sql);
           pstmnt.execute();
         
            JOptionPane.showMessageDialog(null,"Priskirta");
            naujinimas();
        }catch(Exception e)
        {JOptionPane.showMessageDialog(null, e);}
   
    }//GEN-LAST:event_priskirtimgtActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try{
        //String sql="insert into UZDUOCIUDB(ID,UZDUOTIESPRISKIRIMAS,"
          //  + "VYKDANCIOJOPAREIGOS)values(?,?,?)";
     int reiksme = busenaslider.getValue();
     if(reiksme!=100)
     {busenatxt.setText("false");}
     else busenatxt.setText("true");
          String skaicius = priskirimascombo.getSelectedItem().toString();
    uzduotispriskirimastxt.setText(skaicius);
   //String pareigosstr ="select * FROM VARTOTOJAIDB WHERE ID = '"+uzduotispriskirimastxt+"' ";
   String temp=null; 
   if("tomas".equals(skaicius))
    {temp="Programuotojas";}
        else if("simas".equals(skaicius)){
              temp="Front-end programuotojas";  
   }  else if("kristina".equals(skaicius)){
              temp="Back-end programuotojas";  
   }else if("ugne".equals(skaicius)){
              temp="Testuotoja";  
   }
    pareiga.setText(temp);
    //pstmnt=prisijungimas.prepareStatement(sql);
           String value1= idtxt.getText();
      //     int val1=Integer.parseInt(value1);
        String value2=uzduotistxt.getText();
           String value3=uzduotispriskirimastxt.getText();
           String value4=pareiga.getText();
           String value5=busenatxt.getText();
           String sql="update uzduociudb set ID="+ value1+",UZDUOTIS='"+value2+"',UZDUOTIESPRISKIRIMAS='"+value3+"',VYKDANCIOJOPAREIGOS='"+value4+"',BUSENA='"+value5+"' WHERE ID="+value1+""; 
           pstmnt=prisijungimas.prepareStatement(sql);
           pstmnt.execute();
            JOptionPane.showMessageDialog(null,"Redaguota");
     naujinimas();
        }catch(Exception e)
        {JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         close();
        Login temp = new Login();
        temp.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider busenaslider;
    private javax.swing.JTextField busenatxt;
    private javax.swing.JTextField idtxt;
    private javax.swing.JButton istrintibtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField pareiga;
    private javax.swing.JComboBox<String> priskirimascombo;
    private javax.swing.JButton priskirtimgt;
    private javax.swing.JButton sukurtitxt;
    private javax.swing.JLabel usertxt;
    private javax.swing.JTextField uzduotispriskirimastxt;
    private javax.swing.JTextField uzduotistxt;
    // End of variables declaration//GEN-END:variables
}
