/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uzduociu_sarasas;

import com.sun.org.apache.xml.internal.utils.StringComparable;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import org.apache.derby.iapi.sql.compile.CompilerContext;

/**
 *
 * @author Paulius
 */
public class GUIworkers extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    Connection prisijungimas=null;
ResultSet rezultatas=null;
PreparedStatement pstmnt=null;
String naujas;
    public GUIworkers() {
        initComponents();
        prisijungimas = Uzduociu_sarasas.Prisijungti();
        rodymas();
       // combo();
        
    }
public void rodymas()
{
    try{
    String sql="select * from UZDUOCIUDB";
pstmnt=prisijungimas.prepareStatement(sql);
rezultatas=pstmnt.executeQuery();
jTable1.setModel(DbUtils.resultSetToTableModel(rezultatas));
}
catch(Exception e){
//JOptionPane.showMessageDialog(null, e.getMessage());
}
finally{
    try{
        rezultatas.close();
        pstmnt.close();         
    }
    catch(Exception e){}}
}
public void vardas(String sk)
{ String naujas=null;
    naujas=sk;
   // System.out.println(naujas);
//useris.setText(naujas);
String k=null;
k = naujas.toUpperCase().substring(0, (naujas.length()- (naujas.length()-1)) );
usertxt.setText(" Vartotojas : " + k+naujas.substring(1));
    }
private void combo()
{
    try{
        String sql="select * from vartotojaidb where vardas!= 'rimas' ";
        pstmnt=prisijungimas.prepareStatement(sql);
        rezultatas=pstmnt.executeQuery();
        while(rezultatas.next())
        {String veikejas = rezultatas.getString("vardas");
       }
    }catch(Exception ex)
    {JOptionPane.showMessageDialog(null, ex);}
}
private void naujinimas()
    {
        String sql="select * from UZDUOCIUDB";
        try
        {
            pstmnt=prisijungimas.prepareStatement(sql);
            rezultatas =pstmnt.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rezultatas));
        }catch(Exception e)
        {JOptionPane.showMessageDialog(null,e);}finally{try{rezultatas.close();pstmnt.close();}catch(Exception e){}}
    }
public void tikrinimas(String kuris)
{
  naujas=kuris;
    String sql="select distinct UZ.ID, UZDUOTIS, UZDUOTIESPRISKIRIMAS, VYKDANCIOJOPAREIGOS, BUSENA from UZDUOCIUDB UZ, VARTOTOJAIDB VART where UZDUOTIESPRISKIRIMAS= '"+ naujas +"' ";
        try
        {
            pstmnt=prisijungimas.prepareStatement(sql);
            rezultatas =pstmnt.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rezultatas));
        }catch(Exception e)
        {JOptionPane.showMessageDialog(null,e);}finally{try{rezultatas.close();pstmnt.close();}catch(Exception e){}}
    
}
  public void close()
    {
        WindowEvent uzdarymas = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(uzdarymas);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        uzduotistxt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        usertxt = new javax.swing.JLabel();
        busenatxt = new javax.swing.JTextField();
        uzduotispriskirimastxt = new javax.swing.JTextField();
        busenaslider = new javax.swing.JSlider();
        pareiga = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Užduotis", "Užduoties priskirimas", "Vykdančiojo pareigos", "Busena"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("ID");

        jLabel2.setText("Užduotis");

        jLabel5.setText("Būsena");

        idtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtActionPerformed(evt);
            }
        });

        uzduotistxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uzduotistxtActionPerformed(evt);
            }
        });

        jButton3.setText("Redaguoti");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        usertxt.setBackground(new java.awt.Color(0, 0, 153));
        usertxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usertxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usertxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        uzduotispriskirimastxt.setForeground(new java.awt.Color(255, 255, 255));
        uzduotispriskirimastxt.setBorder(null);

        busenaslider.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        busenaslider.setMajorTickSpacing(100);
        busenaslider.setPaintLabels(true);
        busenaslider.setPaintTicks(true);

        pareiga.setForeground(new java.awt.Color(255, 255, 255));
        pareiga.setBorder(null);
        pareiga.setCaretColor(new java.awt.Color(255, 255, 255));

        jMenu1.setText("File");

        jMenuItem1.setText("Atsijungti");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pareiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(107, 107, 107)
                            .addComponent(busenaslider, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(78, 78, 78)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(busenatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(uzduotistxt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(uzduotispriskirimastxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uzduotispriskirimastxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(pareiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(8, 8, 8))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(uzduotistxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(52, 52, 52)
                                .addComponent(busenaslider, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(busenatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtxtActionPerformed

    private void uzduotistxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uzduotistxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uzduotistxtActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        try
        {
            int row =jTable1.getSelectedRow();
            idtxt.setText(jTable1.getModel().getValueAt(row,0).toString());
            uzduotistxt.setText(jTable1.getModel().getValueAt(row,1).toString());
            uzduotispriskirimastxt.setText(jTable1.getModel().getValueAt(row,2).toString());
           // pareiga.setText(jTable1.getModel().getValueAt(row,3).toString());
            busenatxt.setText(jTable1.getModel().getValueAt(row,4).toString());
            
        }catch(Exception ex)
        {JOptionPane.showMessageDialog(null,ex);}
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try{
        //String sql="insert into UZDUOCIUDB(ID,UZDUOTIESPRISKIRIMAS,"
          //  + "VYKDANCIOJOPAREIGOS)values(?,?,?)";
     int reiksme = busenaslider.getValue();
     if(reiksme!=100)
     {busenatxt.setText("false");}
     else busenatxt.setText("true");
      
   //String pareigosstr ="select * FROM VARTOTOJAIDB WHERE ID = '"+uzduotispriskirimastxt+"' ";
    //pstmnt=prisijungimas.prepareStatement(sql);
           String value1= idtxt.getText();
           String value5=busenatxt.getText();
           String sql="UPDATE UZDUOCIUDB set BUSENA='"+value5+"' WHERE ID="+value1+""; 
           pstmnt=prisijungimas.prepareStatement(sql);
           pstmnt.execute();
             tikrinimas(naujas);
            JOptionPane.showMessageDialog(null,"Redaguota");
            naujinimas();
            tikrinimas(naujas);
        }catch(Exception e)
        {JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
       close();
        Login puslapis = new Login();
        puslapis.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIworkers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIworkers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIworkers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIworkers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIworkers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider busenaslider;
    private javax.swing.JTextField busenatxt;
    private javax.swing.JTextField idtxt;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField pareiga;
    private javax.swing.JLabel usertxt;
    private javax.swing.JTextField uzduotispriskirimastxt;
    private javax.swing.JTextField uzduotistxt;
    // End of variables declaration//GEN-END:variables
}
